"""Stable failure reasons, Hebrew recovery guidance, and provider wire codes.

Categories remain broad for runtime recovery. Reasons distinguish the concrete
failure for both the user and the log. Structured codes take precedence over
HTTP defaults and narrowly scoped message fallbacks.
"""

# reason: (runtime category, retry action, user explanation)
ERROR_REASONS = {
    "missing_key": ("auth", "none", "לא הוגדר מפתח API עבור {label}. יש להוסיף מפתח בהגדרות הספק."),
    "invalid_key": ("auth", "none", "מפתח ה-API של {label} נדחה. יש לבדוק שהועתק במלואו ושייך לספק ולאזור שנבחרו."),
    "expired_key": ("auth", "none", "מפתח ה-API של {label} פג תוקף. יש ליצור מפתח חדש ולעדכן אותו בהגדרות."),
    "revoked_key": ("auth", "none", "מפתח ה-API של {label} בוטל או נחסם. יש ליצור מפתח חדש בחשבון הספק."),
    "signin_expired": ("auth", "none", "ההתחברות ל-ChatGPT / Codex פגה או בוטלה. יש להתחבר מחדש בהגדרות הספק."),
    "signin_required": ("auth", "none", "נדרשת התחברות ל-ChatGPT באמצעות Codex בהגדרות הספק."),
    "signin_model_unsupported": ("model_unavailable", "none", "המודל {model} נדחה בחיבור ChatGPT / Codex. יש לעדכן את Codex CLI הרשמי ולרענן את רשימת המודלים בהגדרות סמארטי. אם הדחייה נמשכת, יש לבחור מודל זמין לחשבון או Codex default."),
    "ip_restricted": ("permission", "none", "{label} דחה את כתובת ה-IP הנוכחית. יש לבדוק את רשימת כתובות ה-IP המותרות בחשבון או את הגדרות ה-VPN."),
    "region_restricted": ("permission", "none", "{label} אינו מאפשר שימוש מהמדינה או מהאזור הנוכחיים. יש לבדוק אזורים נתמכים והתאמה בין אזור המפתח לשרת ה-API."),
    "model_permission": ("permission", "none", "לחשבון של {label} אין הרשאה למודל {model}. יש לקבל הרשאה למודל או לבחור מודל שהחשבון מורשה אליו."),
    "permission_denied": ("permission", "none", "למפתח או לחשבון של {label} אין הרשאה לפעולה המבוקשת. יש לבדוק הרשאות API ופרויקט אצל הספק."),
    "credits_exhausted": ("billing_quota", "none", "יתרת הקרדיט של {label} הסתיימה. יש להוסיף קרדיט אצל הספק; ניסיון חוזר לבדו לא יחזיר את הגישה."),
    "organization_spend_limit": ("billing_quota", "none", "הארגון ב-{label} הגיע לתקרת ההוצאה שהוגדרה. יש לעדכן את תקרת ההוצאה בהגדרות הארגון אצל הספק."),
    "project_spend_limit": ("billing_quota", "none", "הפרויקט ב-{label} הגיע לתקרת ההוצאה שהוגדרה. יש לעדכן את תקרת הפרויקט אצל הספק."),
    "account_usage_limit": ("billing_quota", "none", "החשבון ב-{label} הגיע למגבלת השימוש שהספק הקצה לו. יש להמתין לאיפוס או לבקש הגדלת מכסה אצל הספק."),
    "key_spend_limit": ("billing_quota", "none", "מפתח ה-API של {label} הגיע לתקרת הקרדיט שלו. יש לעדכן את מגבלת המפתח אצל הספק."),
    "billing_required": ("provider_setup", "none", "השימוש ב-{label} דורש הפעלת חיוב או השלמת הגדרת תשלום בפרויקט. יש לבדוק זאת במסוף הספק."),
    "quota_exhausted": ("billing_quota", "none", "מכסת החשבון של {label} נוצלה או שאין יתרת שימוש זמינה. יש לבדוק את המכסה והחיוב אצל הספק לפני ניסיון נוסף."),
    "free_quota_exhausted": ("billing_quota", "none", "מכסת השימוש החינמית של {label} הסתיימה. יש לבדוק מתי היא מתאפסת או להפעיל מסלול בתשלום אצל הספק."),
    "daily_quota": ("billing_quota", "none", "המכסה היומית של {label} נוצלה. יש להמתין לאיפוס היומי של הספק או להגדיל את המכסה; המתנה של כמה שניות לא תפתור זאת."),
    "quota_unavailable": ("billing_quota", "none", "{label} מדווח על מכסה אפסית למודל או לפרויקט. יש לבדוק אם המודל זמין במסלול הנוכחי ולהפעיל חיוב או לבחור מודל עם מכסה זמינה."),
    "signin_usage_limit": ("billing_quota", "none", "מכסת השימוש של ChatGPT / Codex הסתיימה. יש להמתין למועד האיפוס שמופיע בחשבון או לעדכן את המסלול."),
    "two_factor_required": ("auth", "none", "{label} דורש אימות דו-שלבי לחשבון. יש להשלים את האימות אצל הספק לפני ניסיון נוסף."),
    "subscription_expired": ("billing_quota", "none", "המינוי של {label} פג תוקף. יש לחדש את המינוי באתר הספק כדי להמשיך להשתמש ב-API."),
    "enterprise_subscription_expired": ("billing_quota", "none", "חבילת הארגון של {label} פגה. יש לפנות למנהל הארגון לחידוש החבילה."),
    "weekly_monthly_quota": ("billing_quota", "none", "המכסה השבועית או החודשית של {label} הסתיימה. יש להמתין למועד האיפוס שהספק מציין בפרטי השגיאה."),
    "five_hour_quota": ("billing_quota", "none", "מכסת חמש השעות של {label} נוצלה ואין יתרה לשימוש נוסף. יש להמתין למועד האיפוס שהספק החזיר או להוסיף יתרה."),
    "weekly_quota": ("billing_quota", "none", "המכסה השבועית של {label} נוצלה ואין יתרה לשימוש נוסף. יש להמתין לאיפוס השבועי או להוסיף יתרה אצל הספק."),
    "five_hour_spend_limit": ("billing_quota", "none", "מכסת חמש השעות של {label} נוצלה ותקרת ההוצאה החודשית מונעת שימוש נוסף. יש להמתין לאיפוס או לעדכן את תקרת ההוצאה."),
    "weekly_spend_limit": ("billing_quota", "none", "המכסה השבועית של {label} נוצלה ותקרת ההוצאה החודשית מונעת שימוש נוסף. יש להמתין לאיפוס או לעדכן את תקרת ההוצאה."),
    "fair_usage_restricted": ("permission", "none", "{label} הגביל את החשבון לפי מדיניות שימוש הוגן. יש לפנות לספק לבירור ולהשבת הגישה."),
    "enterprise_key_only": ("permission", "none", "מפתח ה-API של {label} מוגבל לחבילת הקידוד הארגונית. יש להשתמש במפתח שמתאים למוצר ולכתובת ה-API שנבחרו."),
    "responses_required": ("invalid_request", "none", "המודל {model} דורש את Responses API של OpenAI. יש להשתמש במסלול Responses המתאים למודל הזה."),
    "request_rate": ("rate_limit", "delayed", "נחצתה מגבלת מספר הבקשות של {label}. יש להמתין לאיפוס מגבלת הקצב ולהפחית בקשות מקבילות."),
    "token_rate": ("rate_limit", "delayed", "נחצתה מגבלת הטוקנים לזמן נתון של {label}. יש להמתין לאיפוס ולהקטין את ההקשר או את אורך הפלט."),
    "concurrency_limit": ("rate_limit", "delayed", "מספר הבקשות המקבילות אל {label} עבר את המגבלה. יש להמתין לסיום בקשות פעילות."),
    "in_flight_budget": ("rate_limit", "delayed", "תקציב הבקשות הפעילות של OpenRouter תפוס כרגע. יש להמתין לשחרורו לפי זמן ההמתנה שהספק החזיר."),
    "rate_limit": ("rate_limit", "delayed", "{label} הגביל זמנית את קצב הבקשות. יש להמתין לפי זמן האיפוס של הספק לפני ניסיון נוסף."),
    "context_length": ("request_too_large", "none", "ההקשר שנשלח למודל {model} ב-{label} חורג מחלון ההקשר שלו. יש לקצר את השיחה, לפתוח שיחה חדשה או לבחור מודל עם חלון גדול יותר."),
    "payload_too_large": ("request_too_large", "none", "גוף הבקשה אל {label} גדול מהמותר. יש להקטין או להסיר קבצים מצורפים ולהפחית את גודל התוכן."),
    "output_limit": ("invalid_request", "none", "מגבלת הפלט או תקציב החשיבה שנשלחו למודל {model} אינם תקינים. יש להתאים את אורך הפלט ותקציב החשיבה למגבלות המודל."),
    "unsupported_parameter": ("invalid_request", "none", "המודל {model} ב-{label} אינו תומך בפרמטר שנשלח. יש לבדוק את הפרמטר שמופיע בפרטי השגיאה ואת התאמת המודל לפרוטוקול."),
    "invalid_parameter": ("invalid_request", "none", "{label} דחה ערך של פרמטר בבקשה. יש לבדוק את שם הפרמטר ואת המגבלה שמופיעים בפרטי השגיאה."),
    "stream_required": ("invalid_request", "none", "המודל {model} ב-{label} דורש תשובה בהזרמה. יש להשתמש בבקשת streaming עבור המודל הזה."),
    "tool_dependency_failure": ("invalid_request", "none", "כלי חיצוני או שרת MCP שהספק {label} ניסה להפעיל נכשל. יש לבדוק הרשאות וחיבור של הכלי החיצוני."),
    "invalid_history": ("invalid_request", "none", "{label} דחה את מבנה היסטוריית השיחה או רצף תוצאות הכלים. אפשר לפתוח שיחה חדשה; פרטי הספק מציינים את השדה שנדחה."),
    "invalid_tool_schema": ("invalid_request", "none", "{label} דחה את הגדרת אחד הכלים. פרטי השגיאה מציינים את הכלי או את השדה שאינם תואמים לסכמת הספק."),
    "invalid_attachment": ("invalid_request", "none", "{label} לא הצליח לקרוא את הקובץ או התמונה המצורפים. יש לבדוק שהקובץ תקין ובפורמט ובגודל שהמודל תומך בהם."),
    "unsupported_modality": ("invalid_request", "none", "המודל {model} ב-{label} אינו תומך בסוג הקובץ שנשלח. יש להסיר אותו או לבחור מודל שתומך בתמונה, בקול או במסמך המתאימים."),
    "invalid_request": ("invalid_request", "none", "{label} דחה את מבנה הבקשה. פרטי השגיאה מציינים את הפרמטר או מבנה השיחה שדורשים תיקון."),
    "service_tier": ("provider_setup", "none", "מסלול השירות שהבקשה בחרה ב-{label} אינו מותר לפרויקט. יש לבדוק את מסלולי השירות המותרים בהגדרות הפרויקט."),
    "provider_setup": ("provider_setup", "none", "הפרויקט ב-{label} אינו מוכן לשימוש ב-API. יש לבדוק הפעלת השירות, חיוב והרשאות במסוף הספק."),
    "model_not_found": ("model_unavailable", "none", "המודל {model} לא נמצא אצל {label}. ייתכן שהשם שגוי או שהמודל הוסר; יש לרענן את רשימת המודלים ולבחור מודל זמין."),
    "model_retired": ("model_unavailable", "none", "המודל {model} ב-{label} הוצא משימוש. יש לבחור מודל חלופי ברשימת המודלים העדכנית."),
    "endpoint_not_found": ("provider_setup", "none", "כתובת ה-API המבוקשת אינה קיימת אצל {label}. יש לבדוק את כתובת השרת, גרסת ה-API והנתיב."),
    "routing_unavailable": ("model_unavailable", "none", "אין ב-OpenRouter ספק שעומד בדרישות הניתוב של המודל שנבחר. יש לבדוק מסנני ספקים, פרטיות וזמינות המודל."),
    "content_policy": ("content_blocked", "none", "{label} חסם את הבקשה או את התשובה בגלל מדיניות תוכן או בטיחות. יש לשנות את ניסוח הבקשה בהתאם למדיניות הספק."),
    "safety_blocked": ("content_blocked", "none", "מסנן הבטיחות של {label} חסם את יצירת התשובה. יש לשנות את ניסוח הבקשה בהתאם למדיניות הבטיחות של הספק."),
    "blocklisted_terms": ("content_blocked", "none", "{label} עצר את התשובה בגלל מונחים ברשימת חסימה. יש להסיר או לשנות את המונחים שבבקשה."),
    "prohibited_content": ("content_blocked", "none", "{label} עצר את התשובה בגלל חשש לתוכן אסור. יש לשנות את הבקשה בהתאם למדיניות התוכן של הספק."),
    "sensitive_personal_data": ("content_blocked", "none", "{label} עצר את התשובה בגלל חשש לחשיפת מידע אישי רגיש. יש להסיר מזהים אישיים מהבקשה."),
    "image_safety": ("content_blocked", "none", "{label} חסם את התמונה שנוצרה בגלל מדיניות בטיחות לתמונות. יש לשנות את תיאור התמונה."),
    "image_prohibited": ("content_blocked", "none", "{label} עצר את יצירת התמונה בגלל תוכן אסור. יש לשנות את הבקשה לתמונה בהתאם למדיניות הספק."),
    "image_recitation": ("content_blocked", "none", "{label} עצר את יצירת התמונה בגלל חשש להעתקת תוכן מוגן. יש לבקש תמונה מקורית."),
    "policy_escalation": ("content_blocked", "none", "{label} עצר את הבקשה לפי כלל סינון מוגבר. יש לבדוק את מדיניות הספק ולשנות את הבקשה."),
    "account_disabled": ("permission", "none", "{label} הגביל או השבית את החשבון עקב מדיניות שימוש. יש לבדוק את מצב החשבון מול תמיכת הספק."),
    "recitation": ("content_blocked", "none", "{label} עצר את התשובה בגלל חשש להעתקת תוכן מוגן. יש לבקש סיכום או ניסוח מקורי."),
    "response_token_limit": ("invalid_response", "none", "המודל {model} הגיע למגבלת הפלט לפני שהפיק תשובה מלאה. יש לקצר את הבקשה או להגדיל את מגבלת הפלט בהתאם למודל ולמכסה."),
    "malformed_tool_call": ("invalid_response", "delayed", "המודל {model} החזיר קריאה לכלי בפורמט לא תקין. נדרש ניסיון נוסף לקבלת תשובה תקינה."),
    "unexpected_tool_call": ("invalid_response", "none", "המודל {model} ביקש כלי שלא הופעל בבקשה. יש לבדוק התאמה בין הגדרות הכלים לבין המודל."),
    "too_many_tool_calls": ("invalid_response", "none", "{label} עצר את התשובה לאחר יותר מדי קריאות לכלים ברצף. יש לצמצם את היקף הבקשה."),
    "missing_thought_signature": ("invalid_request", "none", "{label} דחה רצף כלי שחסרה בו חתימת חשיבה. יש לתקן את שימור החתימות בפרוטוקול השיחה או להתחיל שיחה חדשה."),
    "unsupported_language": ("invalid_response", "none", "{label} עצר את התשובה כי השפה שנוצרה אינה נתמכת. יש לנסות שפה נתמכת או מודל אחר."),
    "image_missing": ("invalid_response", "none", "המודל {model} היה אמור להפיק תמונה אך לא הפיק אותה. יש לנסות בקשה אחרת או מודל תמונות זמין."),
    "image_generation_error": ("invalid_response", "delayed", "{label} נתקל בתקלה ביצירת התמונה. אפשר לנסות שוב לאחר המתנה קצרה."),
    "generation_interrupted": ("invalid_response", "none", "{label} עצר את יצירת התשובה מסיבה שלא פורטה. סיבת העצירה המקורית מופיעה בפרטי השגיאה."),
    "empty_response": ("invalid_response", "delayed", "{label} החזיר תשובה ללא טקסט וללא קריאת כלי. נדרש ניסיון נוסף; אם זה חוזר, יש לבדוק את המודל ומגבלת הפלט."),
    "invalid_response": ("invalid_response", "delayed", "{label} החזיר תשובה שאינה תואמת לפרוטוקול ה-API. יש לנסות שוב ולבדוק אם שרת או פרוקסי מחזירים עמוד שגיאה במקום תשובת המודל."),
    "server_error": ("server_overload", "delayed", "אירעה תקלה פנימית בשרת של {label}. אפשר לנסות שוב לאחר המתנה קצרה."),
    "server_overloaded": ("server_overload", "delayed", "שרת המודל ב-{label} עמוס כרגע. יש להמתין או לבחור מודל זמין אחר."),
    "upstream_error": ("server_overload", "delayed", "שרת התיווך של {label} נכשל בתקשורת עם שרת המודל. אפשר לנסות שוב לאחר המתנה קצרה."),
    "service_unavailable": ("server_overload", "delayed", "השירות של {label} אינו זמין כרגע. אפשר לנסות שוב מאוחר יותר ולבדוק את מצב השירות אצל הספק."),
    "connect_timeout": ("timeout", "delayed", "החיבור לשרת של {label} לא נוצר בזמן. יש לבדוק נגישות לשרת, פרוקסי וחומת אש."),
    "read_timeout": ("timeout", "delayed", "השרת של {label} לא החזיר נתונים בזמן. אפשר לנסות שוב או להקטין את ההקשר ואת אורך הפלט."),
    "write_timeout": ("timeout", "delayed", "העלאת הבקשה אל {label} לא הסתיימה בזמן. יש לבדוק את החיבור ולהקטין קבצים מצורפים."),
    "pool_timeout": ("timeout", "delayed", "כל חיבורי ה-API הזמינים ל-{label} תפוסים. יש להמתין לסיום בקשות פעילות."),
    "gateway_timeout": ("timeout", "delayed", "שרת התיווך של {label} הפסיק להמתין לשרת המודל. אפשר לנסות שוב או להקטין את הבקשה."),
    "timeout": ("timeout", "delayed", "הבקשה אל {label} לא הושלמה בזמן. אפשר לנסות שוב ולבדוק זמינות שרת וחיבור."),
    "dns_failure": ("network", "delayed", "לא ניתן לפתור את שם השרת של {label} ב-DNS. יש לבדוק חיבור לאינטרנט, שרת DNS וכתובת שרת ה-API."),
    "proxy_failure": ("network", "delayed", "הפרוקסי נכשל בחיבור אל {label}. יש לבדוק כתובת פרוקסי, הרשאות ונגישות אליו."),
    "proxy_auth_required": ("permission", "none", "שרת הפרוקסי דורש אימות או דחה את פרטי ההתחברות. יש לתקן את הרשאות הפרוקסי לפני ניסיון נוסף אל {label}."),
    "connection_refused": ("network", "delayed", "השרת של {label} סירב לחיבור. יש לבדוק שהוא פועל ושכתובת השרת והפורט נכונים."),
    "connection_reset": ("network", "delayed", "החיבור אל {label} נותק במהלך הבקשה. יש לבדוק יציבות רשת, פרוקסי וסינון."),
    "network_failure": ("network", "delayed", "לא ניתן להתחבר אל {label}. יש לבדוק חיבור רשת, כתובת שרת, VPN וחומת אש."),
    "certificate_expired": ("ssl", "none", "תעודת ה-HTTPS של החיבור אל {label} פגה. יש לבדוק את שעון Windows ואת תוקף תעודת השרת או תעודת הסינון."),
    "certificate_hostname": ("ssl", "none", "תעודת ה-HTTPS אינה תואמת לשם השרת של {label}. יש לבדוק כתובת API ופרוקסי או סינון שמחליפים תעודות."),
    "certificate_untrusted": ("ssl", "none", "לא ניתן לאמת את שרשרת האמון של תעודת ה-HTTPS מול {label}. יש לבדוק אישורי Windows או להגדיר את תעודת השורש של הסינון בהגדרות אמון HTTPS."),
    "tls_configuration": ("ssl", "none", "הגדרת אמון HTTPS המקומית אינה תקינה. יש לבדוק את קובץ תעודת השורש שנבחר בהגדרות."),
    "tls_failure": ("ssl", "none", "משא ומתן ה-HTTPS מול {label} נכשל. יש לבדוק פרוקסי, סינון ותמיכה בפרוטוקול TLS."),
    "client_dependency": ("provider_setup", "none", "רכיב התוכנה הדרוש לחיבור אל {label} חסר או אינו תואם. יש לעדכן את התקנת סמארטי."),
    "local_model_unloaded": ("model_unavailable", "none", "אין מודל טעון בשרת המקומי. יש לטעון מודל בשרת ולבחור אותו בהגדרות סמארטי."),
    "invalid_server_url": ("provider_setup", "none", "כתובת שרת ה-API אינה תקינה. יש להזין כתובת http או https מלאה עם הנתיב והפורט המתאימים."),
    "unknown": ("unknown", "none", "{label} החזיר שגיאה שלא זוהתה. קוד הספק ופרטי האבחון מופיעים בהמשך; יש לצרף אותם לדיווח התקלה."),
}

# These are wire error identifiers, not message fragments.
CODE_REASONS = {
    "invalid_api_key": "invalid_key", "invalidapikey": "invalid_key",
    "api_key_invalid": "invalid_key", "unauthenticated": "invalid_key",
    "authentication_error": "invalid_key", "authentication": "invalid_key",
    "api_key_expired": "expired_key", "api_key_revoked": "revoked_key",
    "api_key_service_blocked": "revoked_key",
    "credit_balance_exhausted": "credits_exhausted",
    "organization_spend_limit_exceeded": "organization_spend_limit",
    "project_spend_limit_exceeded": "project_spend_limit",
    "organization_usage_limit_exceeded": "account_usage_limit",
    "insufficient_quota": "quota_exhausted", "billing_error": "credits_exhausted",
    "payment_required": "credits_exhausted", "insufficient_balance": "credits_exhausted",
    "permission_error": "permission_denied", "permission_denied": "permission_denied",
    "model_not_found": "model_not_found", "unknown_model": "model_not_found",
    "model_decommissioned": "model_retired", "model_deprecated": "model_retired",
    "context_length_exceeded": "context_length", "token_limit_exceeded": "context_length",
    "max_tokens_exceeded": "output_limit", "request_too_large": "payload_too_large",
    "payload_too_large": "payload_too_large", "string_too_long": "payload_too_large",
    "unsupported_parameter": "unsupported_parameter", "invalid_parameter": "invalid_parameter",
    "invalid_argument": "invalid_request", "invalid_request_error": "invalid_request",
    "invalid_request": "invalid_request", "unprocessable": "invalid_request",
    "failed_precondition": "provider_setup", "precondition_failed": "provider_setup",
    "rate_limit_exceeded": "rate_limit", "rate_limit_error": "rate_limit",
    "resource_exhausted": "rate_limit", "slow_down": "request_rate",
    "overloaded_error": "server_overloaded", "server_is_overloaded": "server_overloaded",
    "provider_overloaded": "server_overloaded", "provider_unavailable": "upstream_error",
    "internal_server_error": "server_error", "api_error": "server_error",
    "server_error": "server_error", "billing_not_active": "billing_required",
    "internal": "server_error", "server": "server_error",
    "service_unavailable_error": "service_unavailable", "unavailable": "service_unavailable",
    "content_policy_violation": "content_policy", "refusal": "content_policy",
    "invalid_image": "invalid_attachment", "image_too_large": "invalid_attachment",
    "image_too_small": "invalid_attachment", "unsupported_image_format": "invalid_attachment",
    "image_not_found": "invalid_attachment", "image_download_failed": "invalid_attachment",
    "invalid_prompt": "invalid_history", "timeout": "timeout",
    # DashScope names are case-insensitive; punctuation is preserved.
    "invalidapikey.expired": "expired_key", "invalidapikey.notfound": "invalid_key",
    "arrearage": "credits_exhausted", "allocationquota.freequotaexceeded": "free_quota_exhausted",
    "allocationquota.freetieronly": "free_quota_exhausted",
    "throttling.ratequota": "request_rate", "throttling.allocationquota": "token_rate",
    "throttling": "rate_limit", "accessdenied": "permission_denied",
    "accessdenied.unpurchased": "model_permission", "modelnotfound": "model_not_found",
    "invalidparameter": "invalid_parameter", "datainspectionfailed": "content_policy",
    "serviceunavailable": "service_unavailable", "internalerror": "server_error",
}

PROVIDER_CODE_REASONS = {
    "openai_codex_signin": {"usage_limit_reached": "signin_usage_limit", "usage_limit_exceeded": "signin_usage_limit"},
    "qwen": {"insufficient_quota": "token_rate", "limit_requests": "request_rate", "limit_burst_rate": "request_rate", "allocationquota.freetieronly": "free_quota_exhausted"},
    "zhipu": {
        "1000": "invalid_key", "1001": "missing_key",
        "1003": "expired_key", "1005": "two_factor_required",
        "1113": "credits_exhausted", "1210": "invalid_parameter",
        "1211": "model_not_found", "1212": "unsupported_parameter", "1213": "invalid_parameter", "1214": "invalid_parameter", "1215": "invalid_parameter",
        "1220": "permission_denied", "1221": "model_retired", "1222": "endpoint_not_found",
        "1200": "server_error", "1230": "server_error", "1234": "upstream_error", "1261": "context_length",
        "1301": "content_policy", "1302": "rate_limit",
        "1305": "server_overloaded", "1308": "account_usage_limit",
        "1309": "subscription_expired", "1310": "weekly_monthly_quota", "1311": "model_permission",
        "1313": "fair_usage_restricted", "1314": "enterprise_subscription_expired", "1315": "enterprise_key_only",
        "1316": "five_hour_quota", "1317": "weekly_quota", "1318": "five_hour_spend_limit", "1319": "weekly_spend_limit",
        "1320": "five_hour_spend_limit", "1321": "weekly_spend_limit",
    },
    "moonshot": {"insufficient_balance": "credits_exhausted", "exceeded_current_quota": "quota_exhausted"},
}
