// Browser geometry + real isolated authenticated Core. Model output and native
// IPC are deterministic fixtures; this is not a cloud/native/release claim.
const {browserQA}=require('./ux6_browser_support.cjs');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==';
async function main(){
 const q=await browserQA({env:{CHAT_STREAM_QA:'1'},invoke:async(cmd)=>{
  if(cmd==='stage_attachment')return q.handshake.qa_attachment_path;
  if(cmd==='read_attachment_preview')return [...Buffer.from(png,'base64')];
  if(cmd==='open_chat_link')return true;
  throw Error('Unadapted chat QA IPC: '+cmd);
 }}),{page}=q;
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const output='.codex-local/chat-streaming';await fs.mkdir(output,{recursive:true});
 const select=async title=>{await page.locator('.conversation-row').filter({has:page.getByText(title,{exact:true})}).locator('.conversation-select').click();await page.getByRole('heading',{name:title,exact:true}).waitFor();};
 const frame=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const geometry=()=>page.evaluate(()=>{
  const stage=document.querySelector('.chat-stage'),user=[...stage.querySelectorAll('.chat-message-row--user')].at(-1),bubble=user?.querySelector('.sds-user-bubble'),last=stage.querySelector('.message-list')?.lastElementChild;
  const anchor=[...stage.querySelectorAll('[data-message-id]')].find(node=>node.getBoundingClientRect().bottom>stage.getBoundingClientRect().top+4);
  const block=[...anchor?.querySelectorAll('[data-reading-block]')||[]].find(node=>node.getBoundingClientRect().bottom>stage.getBoundingClientRect().top+4 && node.getClientRects().length);
  return {top:stage.scrollTop,height:parseFloat(stage.style.getPropertyValue('--chat-available-height')),bubble:bubble?.getBoundingClientRect().top-stage.getBoundingClientRect().top,end:last?.getBoundingClientRect().bottom-stage.getBoundingClientRect().top,anchor:anchor?.dataset.messageId,block:block?.dataset.readingBlock,offset:(block||anchor)?.getBoundingClientRect().top-stage.getBoundingClientRect().top};
 });
 const send=async text=>{await page.getByRole('textbox',{name:'הודעה',exact:true}).fill(text);await page.getByRole('textbox',{name:'הודעה',exact:true}).press('Enter');};
 try{
  await page.goto(process.argv[2]||'http://127.0.0.1:1453');await page.locator('.chat-welcome').waitFor();
  await select('מחקר לקראת המפגש');
  await page.locator('.chat-stage').evaluate(node=>node.scrollTop=0);await frame();
  await send('stream-long');await page.getByText('מעבד הנחיה: 37%',{exact:true}).waitFor();
  await page.waitForTimeout(240);let before=await geometry();assert.ok(Math.abs(before.bubble-16)<3,JSON.stringify(before));checks.push('send from older history anchors the latest user bubble at 16px');
  await page.getByText('קטע 1: תשובה חיה בעברית עם English וקישור.',{exact:true}).waitFor();
  assert.equal(await page.locator('.chat-message-row--assistant').last().getByRole('button',{name:'העתק',exact:true}).count(),0);checks.push('real partial text is visible before completion; final copy is absent');
  await page.waitForTimeout(2200);let growing=await geometry();assert.ok(Math.abs(growing.top-before.top)<3);await page.locator('.chat-new-content.is-generating').waitFor();checks.push('long streaming reply keeps its start and shows the animated down control');
  await page.locator('.chat-new-content').click();await page.waitForTimeout(240);let clicked=await geometry();await page.waitForTimeout(700);let later=await geometry();assert.ok(Math.abs(clicked.top-later.top)<3);checks.push('down control is a one-time move and does not start following');
  await page.locator('.chat-stage').evaluate(node=>node.scrollTop-=80);await frame();let reading=await geometry();
  await select('שיחה נוספת');await page.waitForTimeout(4000);await select('מחקר לקראת המפגש');await page.locator('.chat-message-row--user').last().getByText('stream-long',{exact:true}).waitFor();await frame();let returned=await geometry();assert.equal(returned.anchor,reading.anchor);assert.ok(Math.abs(returned.offset-reading.offset)<4,JSON.stringify({reading,returned}));checks.push('return after background completion restores the saved logical reading location across pagination');
  await page.locator('.chat-message-row--assistant').last().getByRole('button',{name:'העתק',exact:true}).waitFor();
  await page.setViewportSize({width:640,height:750});await page.waitForTimeout(320);let resized=await geometry();assert.equal(resized.anchor,returned.anchor,JSON.stringify({resized,returned}));assert.equal(resized.block,returned.block,JSON.stringify({resized,returned}));assert.ok(Math.abs(resized.offset-returned.offset)<4,JSON.stringify({resized,returned}));await page.setViewportSize({width:1380,height:900});await page.waitForTimeout(320);checks.push('responsive resizing preserves the paragraph and intra-block reading offset');
  await page.screenshot({path:output+'/long-reply.png'});
  await page.locator('.chat-stage').evaluate(node=>node.scrollTop=0);await send('stream-short');await page.getByText('מעבד הנחיה: 37%',{exact:true}).waitFor();await select('שיחה נוספת');await page.waitForTimeout(2400);await select('מחקר לקראת המפגש');await page.locator('.chat-message-row--user').last().getByText('stream-short',{exact:true}).waitFor();await frame();let pending=await geometry();assert.ok(Math.abs(pending.bubble-16)<4,JSON.stringify(pending));checks.push('leaving before answer starts restores its user/start anchor after completion');
  await select('בדיקת צירופים');await page.getByRole('button',{name:'הרחב הודעה',exact:true}).waitFor();
  const collapse=page.getByRole('button',{name:'הרחב הודעה',exact:true});
  await collapse.scrollIntoViewIfNeeded();await frame();
  const dimension=await page.locator('.message-content.is-collapsed').evaluate(node=>({height:node.getBoundingClientRect().height,available:parseFloat(node.closest('.chat-stage').style.getPropertyValue('--chat-available-height'))}));
  assert.ok(Math.abs(dimension.height+28-dimension.available*.7)<3,JSON.stringify(dimension));checks.push('long user text collapses to 70% of available chat height');
  const handle=await collapse.boundingBox();await collapse.click();await page.waitForTimeout(240);const expanded=await page.getByRole('button',{name:'כווץ הודעה',exact:true}).boundingBox();assert.ok(Math.abs(handle.y-expanded.y)<3,JSON.stringify({handle,expanded}));await page.getByRole('button',{name:'כווץ הודעה',exact:true}).click();await page.waitForTimeout(240);assert.ok(Math.abs(handle.y-(await collapse.boundingBox()).y)<3);checks.push('user expand and collapse preserve the handle coordinate');
  await page.locator('.chat-stage').evaluate(node=>node.scrollTop=0);const strip=await page.locator('.sent-attachments').evaluate(node=>({scroll:node.scrollWidth,width:node.clientWidth,right:node.firstElementChild.getBoundingClientRect().right,last:node.lastElementChild.getBoundingClientRect().right}));assert.ok(strip.scroll>strip.width);assert.ok(strip.right>strip.last);checks.push('images form one horizontal RTL attachment row above the bubble');
  const thumbnail=page.getByRole('button',{name:'הגדל תמונה: image-0.png',exact:true});await thumbnail.click();const modal=page.getByRole('dialog',{name:'image-0.png',exact:true});await modal.waitFor();await modal.locator('img').click();await page.waitForTimeout(200);assert.equal(await modal.count(),1);await modal.locator('img').evaluate(node=>node.dispatchEvent(new WheelEvent('wheel',{deltaY:-400,bubbles:true,cancelable:true})));assert.ok(await modal.locator('img').evaluate(node=>getComputedStyle(node).transform!=='matrix(1, 0, 0, 1, 0, 0)'));await page.keyboard.press('Escape');await modal.waitFor({state:'detached'});assert.ok(await thumbnail.evaluate(node=>node===document.activeElement));await thumbnail.click();await modal.waitFor();await modal.locator('.attachment-lightbox-view').click({position:{x:10,y:10}});await modal.waitFor({state:'detached'});checks.push('image modal keeps image clicks open, zooms without toolbar, closes outside/Escape and restores thumbnail focus');
  await page.screenshot({path:output+'/attachments.png'});
  await select('שיחה נוספת');await send('stream-tools');await page.locator('.agent-status-text:visible').filter({hasText:/^מכין כלי canvas_manager$/}).waitFor();
  const processPanel=page.locator('.agent-process').last();const summary=processPanel.locator(':scope > summary');let start=await summary.boundingBox();await summary.click();await frame();assert.ok(Math.abs(start.y-(await summary.boundingBox()).y)<3);assert.equal(await processPanel.locator('.is-shimmering').count(),1);await summary.click();await processPanel.locator('.agent-tool-group > summary').last().click();await frame();assert.equal(await processPanel.locator('.is-shimmering').count(),1);checks.push('process disclosure stays stationary and transfers one status shimmer down the hierarchy');
  await page.locator('.agent-status-text:visible').filter({hasText:/^ממתין לאישור הפעלת כלי canvas_manager$/}).first().waitFor();await page.getByRole('button',{name:'אשר',exact:true}).last().click();await page.locator('.agent-status-text:visible').filter({hasText:/^מריץ כלי canvas_manager$/}).first().waitFor();await page.locator('.chat-message-row--assistant').last().getByRole('button',{name:'העתק',exact:true}).waitFor();checks.push('preparing -> durable approval -> running -> completed shares the same tool identity');
  const attach=async()=>{await page.locator('.attachment-picker').setInputFiles({name:'qa-image.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.locator('.pending-attachments').waitFor();};
  await attach();await send('stream-short with image');await page.getByText('מעבד הנחיה: 37%',{exact:true}).waitFor();await page.waitForTimeout(240);const attached=await page.locator('.chat-message-row--user').last().evaluate(node=>({bubble:node.querySelector('.sds-user-bubble').getBoundingClientRect().top-node.closest('.chat-stage').getBoundingClientRect().top,strip:node.querySelector('.sent-attachments').getBoundingClientRect().bottom-node.closest('.chat-stage').getBoundingClientRect().top}));assert.ok(Math.abs(attached.bubble-16)<3,JSON.stringify(attached));assert.ok(attached.strip>0 && attached.strip<16,JSON.stringify(attached));await page.locator('.chat-message-row--assistant').last().getByRole('button',{name:'העתק',exact:true}).waitFor();checks.push('sending a real isolated image keeps the text bubble at the top and clips the attachment to a sliver');
  await attach();await page.getByRole('button',{name:'שליחה',exact:true}).click();await page.getByText('מעבד הנחיה: 37%',{exact:true}).waitFor();await page.waitForTimeout(240);const only=await page.locator('.chat-message-row--user').last().evaluate(node=>({bubbles:node.querySelectorAll('.sds-user-bubble').length,bottom:node.querySelector('.sent-attachments').getBoundingClientRect().bottom-node.closest('.chat-stage').getBoundingClientRect().top}));assert.equal(only.bubbles,0);assert.ok(Math.abs(only.bottom-8)<3,JSON.stringify(only));await page.locator('.chat-message-row--assistant').last().getByRole('button',{name:'העתק',exact:true}).waitFor();checks.push('attachment-only send anchors the strip bottom without an empty text bubble');
  await page.emulateMedia({reducedMotion:'reduce'});await send('stream-long cancel');await page.getByText('קטע 1: תשובה חיה בעברית עם English וקישור.',{exact:true}).last().waitFor();await page.getByRole('button',{name:'עצירה',exact:true}).click();await page.getByText('היצירה נעצרה. התשובה שהתקבלה עד העצירה נשמרה.',{exact:true}).waitFor();assert.ok(await page.locator('.chat-message-row--assistant').last().textContent().then(text=>text.includes('קטע 1:')));assert.equal(await page.locator('.chat-message-row--assistant').last().getByRole('button',{name:'העתק',exact:true}).count(),0);checks.push('reduced motion remains functional; cancellation retains the real partial answer without final actions');
  assert.deepEqual(errors,[]);checks.push('no browser runtime errors');
  await fs.writeFile(output+'/report.json',JSON.stringify({checks,scope:'Edge browser with isolated real Core/auth/replay and deterministic model/native IPC; no live provider, native Tauri or release evidence'},null,2));
  console.log(checks.join('\n'));
 }catch(error){await page.screenshot({path:output+'/failure.png'});await fs.writeFile(output+'/failure.json',JSON.stringify({checks,errors,error:String(error)},null,2));throw error;}finally{await q.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
