// Rendered and behavioral checks for the 16 user corrections, not native evidence.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const base = process.argv[2] || 'http://127.0.0.1:1432';
const output = path.resolve(process.argv[3] || '.codex-local/ux-1/qa/feedback-16/focused');
async function run() {
 await fs.mkdir(output,{recursive:true});
 const browser = await chromium.launch({channel:'msedge',headless:true});
 const context = await browser.newContext({viewport:{width:1380,height:900},acceptDownloads:true});
 const page = await context.newPage();
 const checks=[],errors=[],remote=[],measurements=[];
 page.on('pageerror',e=>errors.push(e.message));
 context.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:')) remote.push(r.url());});
 await context.route('**/*',r=>r.request().url().startsWith(base)||r.request().url().startsWith('data:')?r.continue():r.abort());
 const check=(name,value)=>{assert.ok(value,name);checks.push(name);};
 const b=(name,root=page)=>root.getByRole('button',{name,exact:true});
 const nav=async id=>{await page.locator(`nav button[data-section="${id}"]`).click();await page.waitForTimeout(150);};
 const shot=async name=>page.screenshot({path:path.join(output,`${name}.png`)});
 const modelMenu=async()=>{await page.locator('.ux-model-trigger').click();await page.waitForTimeout(100);};
 const patchFavorites=async favorites=>page.evaluate(favorite_models=>window.__TAURI_INTERNALS__.invoke('core_api',{request:{method:'PATCH',path:'/v2/settings',body:{values:{favorite_models}}}}),favorites);
 const getSwitch=async locator=>locator.evaluate(x=>{const track=x.closest('.source-switch')?x.nextElementSibling:x;const s=getComputedStyle(track),thumb=getComputedStyle(track,'::after');return {w:track.offsetWidth,h:track.offsetHeight,color:s.backgroundColor,border:s.borderColor,thumb:thumb.width,right:thumb.right,top:thumb.top,fill:thumb.backgroundColor,shift:new DOMMatrixReadOnly(thumb.transform).m41};});
 try {
 await page.goto(`${base}/ux-1.html?v=5`,{waitUntil:'networkidle'});
 const draft=page.getByRole('textbox',{name:'כתיבת הודעה',exact:true});
 await draft.focus();
 const focus=await draft.evaluate(x=>{const s=getComputedStyle(x),c=getComputedStyle(x.closest('.ux-composer'));return {outline:s.outlineStyle,shadow:s.boxShadow,border:c.borderColor,outerShadow:c.boxShadow,neutral:c.getPropertyValue('--border').trim()};});
 measurements.push({focus});check('01 composer has no blue focus frame',focus.outline==='none'&&focus.shadow==='none'&&focus.outerShadow==='none'&&focus.border==='rgb(221, 225, 232)');
 check('05 visible sender labels removed',await page.locator('.ux-message-author').count()===0);
 check('09 upper left settings removed, sidebar access retained',await page.locator('.ux-topbar [data-icon="settings"]').count()===0&&await b('הגדרות וספקים').count()===1);
 const circle=async name=>{const data=await b(name).evaluate(x=>{const r=x.getBoundingClientRect(),s=getComputedStyle(x);return {w:r.width,h:r.height,radius:s.borderRadius,bg:s.backgroundColor,filter:getComputedStyle(x.querySelector('img')).filter};});measurements.push({name,...data});check(`06 circle ${name}`,data.w===40&&data.h===40&&data.radius==='50%'&&data.bg==='rgb(57, 123, 250)'&&data.filter.includes('invert(1)'));};
 await circle('הדמיית הכתבה ללא מיקרופון');await draft.fill('בדיקת שליחה');await circle('שליחת הודעת הדגמה');await draft.fill('');
 const process=page.locator('.ux-message .agent-process').last();
 const arrow=async (details,level)=>{for(const expanded of [false,true]){if((await details.getAttribute('open')!==null)!==expanded)await details.locator(':scope >summary').click();await page.waitForTimeout(180);const data=await details.locator(':scope >summary').evaluate(x=>{const arrow=x.querySelector('img:first-child'),text=x.querySelector('span'),tool=x.querySelector('img:not(:first-child)');return {arrow:arrow.getBoundingClientRect().x,text:text.getBoundingClientRect().x,tool:tool?.getBoundingClientRect().x,transform:getComputedStyle(arrow).transform};});measurements.push({level,expanded,...data});check(`04 RTL arrow/tool order ${level}/${expanded}`,data.arrow<data.text&&(data.tool===undefined||data.tool>data.text));check(`04 arrow direction ${level}/${expanded}`,expanded?data.transform==='none':data.transform==='matrix(0, 1, -1, 0, 0, 0)');}};
 await arrow(process,'run');const group=process.locator('.agent-tool-group').first();await arrow(group,'group');const tool=group.locator('.agent-tool-row').first();await arrow(tool,'tool');check('04 original tool input/output remains',await tool.getByText('קלט ופרמטרי הפעלה',{exact:true}).count()===1&&await tool.getByText('פלט הכלי',{exact:true}).count()===1);await shot('activity-rtl');await process.locator(':scope >summary').click();
 for(let i=0;i<24;i++)await b('שיחה חדשה').click();
 const fixed=await page.locator('.ux-history>.ux-new-chat,.ux-history>.ux-search').evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().y));
 const history=page.locator('.ux-history-scroll');check('02 history list really overflows',await history.evaluate(x=>x.scrollHeight>x.clientHeight));await history.evaluate(x=>x.scrollTop=x.scrollHeight);
 const after=await page.locator('.ux-history>.ux-new-chat,.ux-history>.ux-search').evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().y));check('02 new chat/search fixed while history scrolls',JSON.stringify(fixed)===JSON.stringify(after));
 const scrollColor=await history.evaluate(x=>getComputedStyle(x).scrollbarColor);measurements.push({scrollColor});check('03 light gray history scrollbar',scrollColor.includes('rgb(203, 208, 216)'));await shot('history-fixed');
 await b('פעולות שיחה').click();check('11 conversation actions vertical and input free',await page.locator('.ux-conversation-menu button').count()===4&&await page.locator('.ux-popup input').count()===0&&await page.locator('.ux-conversation-menu').evaluate(x=>getComputedStyle(x).flexDirection==='column'));check('11 horizontal ellipsis',await page.locator('.ux-topbar .ux-conversation-menu-trigger img').evaluate(x=>getComputedStyle(x).transform==='matrix(0, 1, -1, 0, 0, 0)'));await b('שינוי שם').click();
 const rename=page.getByRole('dialog',{name:'שם השיחה',exact:true});check('11 centered focused rename dialog',await rename.evaluate(x=>{const r=x.getBoundingClientRect();return Math.abs(r.x+r.width/2-innerWidth/2)<1&&Math.abs(r.y+r.height/2-innerHeight/2)<1&&document.activeElement===x.querySelector('input');}));await rename.getByRole('textbox').fill('שם שיחה מעודכן');await shot('rename-centered');await rename.getByRole('textbox').press('Enter');check('11 rename saved on Enter',(await page.locator('.ux-topbar strong').innerText())==='שם שיחה מעודכן');await b('פעולות שיחה').click();await b('שינוי שם').click();await rename.getByRole('textbox').fill('ללא שמירה');await b('ביטול',rename).click();check('11 cancel preserves name',(await page.locator('.ux-topbar strong').innerText())==='שם שיחה מעודכן');
 await modelMenu();check('16 providers on physical right',await page.locator('.ux-model-columns').evaluate(x=>x.children[0].getBoundingClientRect().x>x.children[1].getBoundingClientRect().x));await b('Google 1').hover();check('16 provider browsing retains active selection',(await page.locator('.ux-model-trigger').innerText()).includes('GPT'));await b('OpenAI · חשבון ChatGPT 1').click();await page.getByRole('menuitemradio',{name:/Codex/}).click();await modelMenu();check('16 reasoning and honest two period quota',await page.getByRole('combobox',{name:'רמת חשיבה בהדגמה'}).count()===1&&await page.locator('.ux-model-quota>div').count()===2);await page.getByRole('combobox',{name:'רמת חשיבה בהדגמה'}).selectOption('מעמיקה');await page.keyboard.press('Escape');await modelMenu();check('16 per conversation reasoning retained',await page.getByRole('combobox',{name:'רמת חשיבה בהדגמה'}).inputValue()==='מעמיקה');
 await b('OpenAI · חשבון ChatGPT 1').focus();await page.keyboard.press('ArrowLeft');check('16 left arrow enters model column',await page.locator('.ux-model-list button').first().evaluate(x=>x===document.activeElement));await page.keyboard.press('ArrowRight');check('16 right arrow enters provider column',await b('OpenAI · חשבון ChatGPT 1').evaluate(x=>x===document.activeElement));await shot('models-two-columns');await page.keyboard.press('Escape');check('16 Escape restores model trigger',await page.locator('.ux-model-trigger').evaluate(x=>x===document.activeElement));
 const fullFavorites=await page.evaluate(async()=>{const {models}=await import('/src/ux1/data.ts');return models.map(m=>({provider:m.providerId,model:m.modelKey}));});await patchFavorites(fullFavorites);await modelMenu();check('16 favorites from all 18 provider catalogs',await page.locator('.ux-provider-list button').count()===18);check('16 separate provider scroll',await page.locator('.ux-provider-list').evaluate(x=>x.scrollHeight>x.clientHeight));await b('Anthropic 2').click();check('16 new favorite from settings catalog visible',await page.getByRole('menuitemradio',{name:/anthropic-reasoning-demo/}).count()===1);await page.getByRole('menuitemradio',{name:/anthropic-reasoning-demo/}).click();check('16 selected provider shown in composer',(await page.locator('.ux-model-trigger').innerText()).includes('Anthropic'));await patchFavorites([...fullFavorites].reverse());await modelMenu();check('16 saved favorite order retained',(await page.locator('.ux-provider-list button').first().innerText()).includes('מקומי'));await page.keyboard.press('Escape');await patchFavorites([]);await modelMenu();check('16 active model fallback with no favorites',await page.locator('.ux-model-list [aria-checked="true"]').count()===1&&await page.locator('.ux-provider-list button').count()===1);await page.keyboard.press('Escape');await patchFavorites(fullFavorites);
 await b('פתיחת סביבת העבודה').click();check('10 empty launcher instead of Markdown',await page.locator('.ux-workbench-launch-grid button').count()===5&&await page.locator('.ux-document-pane:visible').count()===0);await shot('workspace-launcher');await page.locator('.ux-workbench-launch-grid button').filter({hasText:'מסוף'}).click();check('10 launcher selects terminal',await page.locator('.terminal-panel:visible').count()===1);await b('סגירת סביבת העבודה').click();await b('פתיחת סביבת העבודה').click();check('10 reopens empty launcher',await page.locator('.ux-workbench-launcher').isVisible());await b('סגירת סביבת העבודה').click();
 await b('הגדרות וספקים').click();check('07 return on right with right arrow',await b('חזרה לשיחה').evaluate(x=>x.getBoundingClientRect().x>innerWidth/2&&x.querySelector('img').dataset.icon==='forward'));check('07 single management title',await page.getByText('ניהול והגדרות',{exact:true}).count()===1);check('08 group jump removed',await page.getByRole('combobox',{name:'קפיצה לקבוצת הגדרות'}).count()===0);await page.getByRole('checkbox',{name:'הצג הגדרות מתקדמות',exact:true}).check();await page.waitForTimeout(180);
 const settingSwitch=await getSwitch(page.locator('.source-advanced-pill .source-switch input'));await nav('tools');const toolSwitch=await getSwitch(page.locator('.source-tool-toggle input').first());measurements.push({settingSwitch,toolSwitch});check('13 tool/settings switches consistent',JSON.stringify(settingSwitch)===JSON.stringify(toolSwitch));await shot('tools-switches');await nav('settings_advanced');
 const ssl=await page.locator('.source-ssl-card header').evaluate(x=>[...x.querySelectorAll('h3,b,small,p')].map(e=>({font:getComputedStyle(e).fontFamily,weight:Number(getComputedStyle(e).fontWeight)})));measurements.push({ssl});check('12 SSL uses candidate typography',ssl.every(x=>x.font.includes('Segoe UI')&&x.weight<=600));await page.locator('.source-ssl-card').scrollIntoViewIfNeeded();await shot('ssl-fonts');
 const numbers=await page.locator('.source-settings-control input[type="number"]').evaluateAll(xs=>xs.filter(x=>x.getClientRects().length).map(x=>x.getBoundingClientRect().width));check('14 numeric fields compact',numbers.length>=6&&numbers.every(w=>w<=112));await page.locator('[data-setting-path="command_timeout_seconds"]').scrollIntoViewIfNeeded();await shot('compact-numbers');
 // Chromium returns the input style for this native shadow pseudo-element.
 // Verify track geometry/fill here and inspect the rendered no-handle screenshot.
 const range=page.locator('.range-field input[type="range"]').first();await range.scrollIntoViewIfNeeded();const rangeData=await range.evaluate(x=>({height:x.getBoundingClientRect().height,bg:getComputedStyle(x).backgroundImage,path:x.closest('[data-setting-path]').dataset.settingPath}));measurements.push({rangeData});check('15 filled thick pill range geometry',rangeData.height===24&&rangeData.bg.startsWith('linear-gradient'));
 await range.press('Home');await page.waitForTimeout(100);await range.press('ArrowLeft');await page.waitForTimeout(100);await range.press('End');await page.waitForTimeout(150);const rangeValue=await range.inputValue();check('15 keyboard saves unlimited sentinel',rangeValue==='31'&&await page.evaluate(()=>window.__UX1_DEMO__.settings().values.max_agent_loops===0)&&await page.locator('[data-setting-path="max_agent_loops"] output').innerText()==='ללא הגבלה');
 const box=await range.boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await page.waitForTimeout(160);check('15 pointer changes and saves value',(await range.inputValue())!==rangeValue&&await page.evaluate(({key,value})=>String(window.__UX1_DEMO__.settings().values[key])===value,{key:rangeData.path,value:await range.inputValue()}));await shot('filled-sliders');
 await nav('settings_ai');await page.locator('[data-setting-path="api_mode"] select').selectOption('openai');await page.locator('.source-model-picker-current').click();const star=page.getByRole('button',{name:'הסר gpt-demo מהמועדפים',exact:true});await star.click();await page.keyboard.press('Escape');await b('חזרה לשיחה').click();await modelMenu();await b('OpenAI 1').click();check('16 settings favorites reflected in main menu',await page.getByRole('menuitemradio',{name:/GPT · מודל הדגמה/}).count()===0&&await page.getByRole('menuitemradio',{name:/openai-reasoning-demo/}).count()===1);await page.keyboard.press('Escape');
 for(const theme of ['light','dark'])for(const width of [360,900,1380]) {
  await page.setViewportSize({width,height:653});await page.goto(`${base}/ux-1.html?v=5&theme=${theme}`,{waitUntil:'networkidle'});await modelMenu();const data=await page.locator('.ux-popup-models').evaluate(x=>{const r=x.getBoundingClientRect();return {left:r.left,right:r.right,bottom:r.bottom,top:r.top,w:x.clientWidth,scroll:x.scrollWidth};});check(`16 popup contained ${theme}/${width}`,data.left>=0&&data.right<=width&&data.top>=0&&data.bottom<=653&&data.scroll<=data.w);await shot(`models-${theme}-${width}`);await page.keyboard.press('Escape');
  await page.getByRole('textbox',{name:'כתיבת הודעה',exact:true}).fill('בדיקת פעולה');await circle('שליחת הודעת הדגמה');await b('שליחת הודעת הדגמה').click();await circle('עצירת ההדגמה');await b('עצירת ההדגמה').click();await shot(`chat-${theme}-${width}`);
  await b('פתיחת סביבת העבודה').click();check(`10 launcher contained ${theme}/${width}`,await page.locator('.ux-artifact').evaluate(x=>x.scrollWidth<=x.clientWidth));await shot(`launcher-${theme}-${width}`);await b('סגירת סביבת העבודה').click();
  if(width===360){await b('פתיחת רשימת שיחות').click();await b('הגדרות וספקים').click();check(`09 narrow history retains settings ${theme}`,await page.locator('.ux-management-root').isVisible());await b('חזרה לשיחה').click();}
 }
 check('isolated local bridge and no missing paths',await page.evaluate(()=>window.__UX1_DEMO__.isolated&&!window.__UX1_DEMO__.trace.some(x=>x.unsupported)));
 check('no runtime errors or remote requests',errors.length===0&&remote.length===0);
 console.log(JSON.stringify({checks:checks.length,output}));
 } catch(e) {await shot('failure');throw e;} finally {await fs.writeFile(path.join(output,'report.json'),JSON.stringify({checks,errors,remote,measurements},null,2));await browser.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
